command: ["sh", "start.sh"]

env:
  # Databricks Connection
  # Note: DATABRICKS_HOST, DATABRICKS_CLIENT_ID, and DATABRICKS_CLIENT_SECRET 
  # are automatically provided by Databricks Apps
  - name: DATABRICKS_HTTP_PATH
    valueFrom: http_path
  
  # OMOP Schema Configuration
  - name: OMOP_CATALOG
    value: "vantage_rwe"
  - name: OMOP_SCHEMA
    value: "omop"
  
  # Optional: Databricks Genie Space ID
  - name: DATABRICKS_GENIE_SPACE_ID
    valueFrom: genie_space_id
  
  # API Configuration
  - name: API_HOST
    value: "0.0.0.0"
  - name: API_PORT
    value: "8000"
  # CORS: Supports wildcards (e.g., https://*.databricks.com matches all Databricks workspaces)
  # The backend automatically converts wildcard patterns to regex for proper CORS validation
  - name: CORS_ORIGINS
    value: "http://localhost:3000,https://*.databricks.com"
  
  # SSL Configuration
  - name: DATABRICKS_VERIFY_SSL
    value: "true"
  
  # React App Configuration (use relative URL for Databricks Apps)
  - name: REACT_APP_API_URL
    value: "/api/v1"
